### ISSUE TITLE
Problem with 'event'

### ISSUE THREAD

**Issue by Olivercomputing** [JoelTipke/KendoUI-MVC-DynamicFilteredColumn#1]
When I try your approach here, I run into problems with the javascript function to retrieve the associated data value, which is the core problem to be solved:

```
<script>
    function getParentId() {
        var row = $(event.srcElement).closest("tr");
        var grid = $(event.srcElement).closest("[data-role=grid]").data("kendoGrid");
        var dataItem = grid.dataItem(row);
        return { ProductID: dataItem.ProductID };
    }
</script>
```

When I try this with the latest incarnation of Kendo grid, I get 'ReferenceError: event is not defined', when $(event.srcElement) is attempted to be evaluated. 

I was wondering if you knew of a solution to this issue, or if there is now some better, Telerik-supported way of retrieving associated column values?

**Comment by JoelTipke** [comment]
Hello, this approach works fine with the latest version of Kendo MVC (2015.1.318). What's the exact error message you are getting?

**Comment by Olivercomputing** [comment]
As mentioned above,  'ReferenceError: event is not defined', on the call from the 'DropDownListFor' from the .Data reference.  When I breakpoint in Firebug in that function, indeed event is not defined. Is that a variable that's supposed to be set by the Kendo grid?

**Comment by JoelTipke** [comment]
Ok thanks for the reply! I think this is firefox specific. See this post: http://stackoverflow.com/questions/4581976/window-event-srcelement-not-working-in-firefox . I will try and modify the sample.

**Comment by Olivercomputing** [comment]
Apparently, that is the issue. I just tried Chrome and it appears to be working as expected.

It's a sad commentary on Telerik that they haven't provided a means to cleanly do this within their API. Being able to access the entire data row rather than an isolated column value is a very common need. Your code is useful and the only mechanism I've seen so far to accomplish that task, but the approach suffers from these sort of browser inconsistencies and dependency on very specific HTML/DOM elements in the grid in the future that might break and be hard to track down. Not a critique of what you did, but of the necessity of having to hack into this stuff.

**Comment by JoelTipke** [comment]
Agreed and I appreciate the comment! I will work on an update that takes into account this issue. Will keep you posted. Thanks!

**Comment by JoelTipke** [comment]
I'm still reviewing options and the best approach on this. One possible solution, use this function in the editor template. 

```
    function getParentId() {
    var row = $("#ShipperID").closest("tr");
    var grid = $("#ShipperID").closest("[data-role=grid]").data("kendoGrid");
    var dataItem = grid.dataItem(row);
    return { ProductID: dataItem.ProductID };
}
```

Not as nice as I'd like but should work and has no dependency on srcElement. 

If you do not need batch editing, take a look here: https://github.com/telerik/ui-for-aspnet-mvc-examples/tree/master/grid/grid-editing-cascading-dropdownlist .

**Comment by Olivercomputing** [comment]
Thanks, Joel, I'll give that a shot. My current feeling is that, after all of the ongoing hassles with Telerik's software, I'm actively looking for less buggy and more flexible alternatives. But for the time being, it's what I'm using.

**Comment by JoelTipke** [comment]
Closing this issue, as this turned out to a be a browser specific issue.
